iswandb: true

log_dir_base: "../../Models/1321_CRN_main_causalF0_ConvLstm"
save_freq: 10
device: "cuda:3"
epochs: 251
batch_size: 30
batch_size_eval: 5
pretrained_model: ""
load_only_params: false
fp16_run: false
auto_weight: true

train_data: "../../Data/train_list.txt"
val_data: "../../Data/val_list.txt"

ASR_config: "../../Utils/ASR/config.yml"
# ASR_path: "Utils/ASR/epoch_00100.pth"
# F0_path: "Utils/JDC/bst.t7"
# F0_path: "../../Utils/JDC/epoch_00100_vector.pth"
# ASR_path: "../../Utils/ASR/epoch_00200_vector.pth"
# F0_path: "../../Utils/JDC/vector_norm_augment.pth"

# F0_path: "../../Utils/JDC/50speakers.pth"
# F0_path: "../../Utils/JDC/50speakers_cliploss.pth"
F0_path: "../../Utils/JDC/50spk_causal.pth"
ASR_path: "../../Utils/ASR/vector_norm_augment.pth"
preprocess_params:
  sr: 24000
  spect_params:
    n_fft: 2048
    win_length: 1200
    hop_length: 300

model_params:
  dim_in: 64
  style_dim: 64
  latent_dim: 16
  num_domains: 20
  max_conv_dim: 512
  n_repeat: 4
  w_hpf: 0
  F0_channel: 256

loss_params:
  g_loss:
    lambda_sty: 1.
    lambda_cyc: 5.
    lambda_ds: 1.
    lambda_norm: 1.
    lambda_asr: 10.
    lambda_f0: 5.
    lambda_con: 20.
    lambda_clip: 3.
    lambda_f0_sty: 0.1
    lambda_adv: 2.
    lambda_adv_cls: 0.5
    norm_bias: 0.5
  d_loss:
    lambda_reg: 1.
    lambda_adv_cls: 0.1
    lambda_con_reg: 10.
  
  adv_cls_epoch: 50
  con_reg_epoch: 30
  con_emb_epoch: 10
  clip_epoch: 72

optimizer_params:
  lr: 0.0001
